service: serverless-template

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${self:custom.region.${self:custom.stage}}
  deploymentBucket:
    name: serverless-deploys.${self:custom.region.${self:custom.stage}}
  environment:
    REGION: ${self:provider.region}

custom:
  stage: ${opt:stage, self:provider.stage}
  region:
    prod: eu-south-1
    dev: eu-south-1

functions:
  hello:
    handler: src/app.hello
    events:
      - http:
          path: /
          method: GET
          cors: true
